Web service report
katiasuya/parentheses pull request #5
Opened 2021-01-21 21:14 UTC by katiasuya

2021-01-22 08:12 UTC, papahmsolo requested changes
Looks very good!

- Add info about how to generate a report
- We need to handle the situation when the response from the service was not successful.

2021-01-22 08:12 UTC, papahmsolo commented on report.go
> +var Lens = []int{2, 4, 6, 8, 10}
Do we need this slice?

2021-01-22 08:12 UTC, papahmsolo commented on report.go
> +			resp, err := http.Get("http://localhost:8000/generate?n=" + strconv.Itoa(n))
Let's extract the URL into a constant

2021-01-22 13:51 UTC, papahmsolo requested changes
Cool!

Let's not terminate the report upon the first error we encounter, log it and move on

2021-01-22 13:51 UTC, papahmsolo commented on README.md
> +To generate a report, run the service and call it using GET method to /generate, passing a length n to it as a query parameter.
How do I run the server and how to generate the report?

2021-01-22 13:51 UTC, papahmsolo commented on report.go
> +		length += 2
We can move `count` and `length` into the `for` statement

2021-01-22 13:51 UTC, papahmsolo commented on report.go
> +			resp, err := http.Get(URLGenerate + strconv.Itoa(length))
We're evaluating the same url N times

2021-01-25 11:14 UTC, papahmsolo requested changes
Very good!

Note, that you have two `main` functions in the same package in `report.go` and `main.go`

2021-01-25 11:14 UTC, papahmsolo commented on report.go
> +		reportURL := URLGenerate + strconv.Itoa(length)
You can use `fmt.Sprint(length)` to add `n` to URL or make `reportURL` a template and use `Sprintf`

2021-01-25 11:14 UTC, papahmsolo commented on report.go
> +			}
Looks like we're duplicating the `ioutil.ReadAll(resp.Body)`

2021-01-25 12:35 UTC, papahmsolo requested changes
Cool!

It makes sense to call the generate service concurrently as the requests are independent.

2021-01-25 12:35 UTC, papahmsolo commented on report/report.go
> +			}
- Let's first check the error
- Let's not terminate the report if an error occurs, we can log it and consider the sequence as unbalanced

2021-01-26 07:58 UTC, papahmsolo requested changes
There's a data race in your code, try running it with `-race` flag

2021-01-27 12:03 UTC, papahmsolo requested changes

2021-01-27 12:03 UTC, papahmsolo commented on report/report.go
> +			}
This is waiting to receive from the channel, so it won't go to the next iteration until it receives from `isBalanced`

2021-01-28 10:39 UTC, papahmsolo requested changes
Cool, let's make some adjustments

2021-01-28 10:39 UTC, papahmsolo commented on report/report.go
> +	return body, nil
You can return a string instead of []byte, which will save you a conversion.

2021-01-28 10:39 UTC, papahmsolo commented on report/report.go
> +			}()
So you're spinning up `numRequests` workers here, cool. Note, that if you `return` in this function the goroutine finishes execution, and the worker it's no longer a worker :)

2021-01-28 10:55 UTC, katiasuya commented on report/report.go
> +			}()
You're right!

2021-01-28 14:50 UTC, papahmsolo approved these changes
Good job

2021-01-28 14:50 UTC, merged